name: build-latest
on:
  workflow_dispatch:
    inputs:
      distro:
        description: Base image distro
        required: true
        default: debian
      imageVersion:
        description: Base distro image version/release
        required: true
        default: bullseye
      imageVariant:
        description: Base image variant
        required: true
        default: slim
  push:
jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build base image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: base_build
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_REPO }}/postgis:${{ github.event.inputs.distro }}-${{ github.event.inputs.imageVersion }}-${{ github.event.inputs.imageVariant }}
