name: build-latest
on:
#  workflow_dispatch:
#    inputs:
#      distro:
#        description: Base image distro
#        required: true
#        default: debian
#      imageVersion:
#        description: Base distro image version/release
#        required: true
#        default: bullseye
#      imageVariant:
#        description: Base image variant
#        required: true
#        default: slim
  push:
  pull_request:
jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      latest-ref: refs/heads/develop
    strategy:
      matrix:
        postgresMajorVersion:
          - 13
        postgisMajorVersion:
          - 3
        postgisMinorRelease:
          - 1
        include:
          - distro: debian
            imageVersion: bullseye
            imageVariant: slim
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get build cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ matrix.distro }}-${{ matrix.imageVersion }}-${{ matrix.imageVariant }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ matrix.distro }}-${{ matrix.imageVersion }}-${{ matrix.imageVariant }}-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build base image
        id: docker_build_base
        uses: docker/build-push-action@v2
        with:
          context: base_build
          file: base_build/Dockerfile
          push: false
          load: true
          tags: ${{ secrets.DOCKERHUB_REPO }}/postgis:base-${{ matrix.distro }}-${{ matrix.imageVersion }}-${{ matrix.imageVariant }}
          build-args: |
            GENERATE_ALL_LOCALE=0
            DISTRO=${{ matrix.distro }}
            IMAGE_VERSION=${{ matrix.imageVersion }}
            IMAGE_VARIANT=${{ matrix.imageVariant }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build prod image
        id: docker_build_prod
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: false
          load: true
          tags: ${{ secrets.DOCKERHUB_REPO }}/postgis:${{ matrix.postgresMajorVersion }}-${{ matrix.postgisMajorVersion }}.${{ matrix.postgisMinorRelease }}
          build-args: |
            DISTRO=${{ matrix.distro }}
            IMAGE_VERSION=${{ matrix.imageVersion }}
            IMAGE_VARIANT=${{ matrix.imageVariant }}
            POSTGRES_MAJOR_VERSION=${{ matrix.postgresMajorVersion }}
            POSTGIS_MAJOR_VERSION=${{ matrix.postgisMajorVersion }}
            POSTGIS_MINOR_VERSION=${{ matrix.postgresMinorVersion }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  run-scenario-tests:
    runs-on: ubuntu-latest
    needs: [ build-image ]
    strategy:
      matrix:
        postgresMajorVersion:
          - 13
        postgisMajorVersion:
          - 3
        postgisMinorRelease:
          - 1
        scenario:
          - datadir_init
          - streaming_replication
          - collations
          - extensions
          - logical_replication
        include:
          - distro: debian
            imageVersion: bullseye
            imageVariant: slim
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get build cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ matrix.distro }}-${{ matrix.imageVersion }}-${{ matrix.imageVariant }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ matrix.distro }}-${{ matrix.imageVersion }}-${{ matrix.imageVariant }}-

      - name: Build base image for testing
        id: docker_build_base
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: false
          load: true
          tags: ${{ secrets.DOCKERHUB_REPO }}/postgis:manual-build
          build-args: |
            DISTRO=${{ matrix.distro }}
            IMAGE_VERSION=${{ matrix.imageVersion }}
            IMAGE_VARIANT=${{ matrix.imageVariant }}
            POSTGRES_MAJOR_VERSION=${{ matrix.postgresMajorVersion }}
            POSTGIS_MAJOR_VERSION=${{ matrix.postgisMajorVersion }}
            POSTGIS_MINOR_VERSION=${{ matrix.postgresMinorVersion }}
          cache-from: type=local,src=/tmp/.buildx-cache

      - name: Build image for testing
        id: docker_build_testing_image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.test
          push: false
          tags: ${{ secrets.DOCKERHUB_REPO }}/postgis:manual-build
          load: true
      - name: Run scenario test
        run: |
          pushd scenario_tests/${{ matrix.scenario }}
          ./test.sh
          popd
